# Generated by Django 4.1.7 on 2023-03-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('passport_number', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=14)),
                ('country', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('work_permit_status', models.CharField(choices=[('before process', 'BEFORE PROCESS'), ('Free', 'FREE'), ('ready', 'READY')], default='before processing', max_length=14)),
                ('work_permit_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, unique=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('left_to_pay', models.IntegerField(default=0)),
                ('rate_before_starting', models.IntegerField(default=0)),
                ('rate_ready', models.IntegerField(default=0)),
                ('partner_login', models.CharField(max_length=200, unique=True)),
                ('rate_visa', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateTimeField()),
                ('amount', models.IntegerField(default=0)),
                ('settlement_name', models.CharField(max_length=200)),
                ('partner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_photo', models.FileField(upload_to='users/static/uploads/')),
                ('cv', models.FileField(upload_to='users/static/uploads/')),
                ('photo', models.FileField(upload_to='users/static/uploads/')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
    ]
