# Generated by Django 4.1.7 on 2023-03-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_partner_partner_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(default='partner', max_length=255)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('partner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partner')),
            ],
        ),
    ]
