# Generated by Django 4.1.7 on 2023-03-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passport', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.IntegerField(default=0)),
                ('country_outside', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
    ]
